services:
  database:
    restart: unless-stopped
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # Add persistent volume

  backend:
    restart: unless-stopped

    build:
      context: ./backend
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "5000:5000"

  frontend:
    restart: unless-stopped

    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
