
services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    environment:
      DB_URI: postgresql://myuser:mypassword@database:5432/mydb

    depends_on:
      - database
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
