services:
  database:
    restart: unless-stopped
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: backend/Dockerfile
    working_dir: /app
    volumes:
      - ./backend:/app/backend
    environment:
      - PYTHONPATH=/app:/app/backend
    ports:
      - "5000:5000"
    command: python backend/app.py


  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE=/api

volumes:
  db_data: