services:
  database:
    container_name: database
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./backend:/app/backend
      - media_uploads:/app/media_uploads
    environment:
      - PYTHONPATH=/app:/app/backend
    depends_on:
      - database
    ports:
      - "5000:5000"
    networks:
      - app_network
    command: python backend/app.py

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
  media_uploads:
